### ISSUE TITLE
start it

### ISSUE THREAD

**Issue by con-gif** [ilanbarr/Sportsbetting-Site#1]
yo, I was reading your source, I dont quite get it how should I initialise the script, like how do I implement the database and initialise the main.py file ? Thanks

**Comment by ilanbarr** [comment]
You can disregard the python as I didn't end up using flask. I set up the sql database on an AWS server

**Comment by con-gif** [comment]
Ah I see, alright. Is the source and the sql database from the AWS Server up for grabs ? I would like to continue developing the source and make an actual betting site out of it but I cba starting from scratch. 
Bless you
